/**
 * Infrastructure-independent reconciliation contract shared by every Control
 * API mutation that observes desired vs. actual runtime state.
 *
 * The contract deliberately mirrors the durable fields listed in
 * `docs/autodev-console-target-state.md` section 5 "Control plane":
 * desired state, actual state, desired generation, observed generation,
 * diff, convergence status (`converged` | `pending` | `error` |
 * `not-observed`), last apply, last observation, last error, and a bounded
 * operation history.
 *
 * The rule derivations in `./rules.ts` are pure and infrastructure-free so
 * they can be exercised in unit tests without touching disk, the network,
 * the router, or the Control API. Runtime and Data layers construct
 * evidence and feed it through these rules; Console renders the resulting
 * status.
 */

/** Convergence status of a desired-state mutation against observed reality. */
export type ConvergenceStatus =
  "converged" | "pending" | "error" | "not-observed";

/**
 * Bounded redacted diff summary that a Control API mutation surfaces. No
 * raw prompt text, tokens, or request bodies ever travel through this
 * shape; it is safe to expose on Console detail pages and to write into
 * audit sinks.
 */
export interface ReconciliationDiff {
  /** One-line, redacted summary of what changed. */
  readonly summary: string;
  /**
   * Stable hash or compact identifier that uniquely distinguishes this
   * applied state from earlier applied states for the same resource.
   */
  readonly identifier: string;
}

export interface ReconciliationEvidence {
  /**
   * Hash or compact identifier the operator-facing mutation produced. This
   * is the desired generation: "what did we ask the runtime to apply?"
   */
  readonly desiredGeneration: string | null;
  /**
   * Hash or compact identifier the runtime actually observed after the
   * apply (e.g. generated projection file content hash, effective routing
   * policy state). `null` when the runtime has not yet observed the new
   * generation.
   */
  readonly observedGeneration: string | null;
  /** RFC3339 timestamp of the most recent successful apply. */
  readonly lastApplyAt: string | null;
  /** RFC3339 timestamp of the most recent runtime observation. */
  readonly lastObservationAt: string | null;
  /** Bounded redacted error message; never the raw stack or body. */
  readonly lastError: string | null;
}

export interface ReconciliationStatus {
  readonly convergence: ConvergenceStatus;
  readonly desiredGeneration: string | null;
  readonly observedGeneration: string | null;
  readonly lastApplyAt: string | null;
  readonly lastObservationAt: string | null;
  readonly lastError: string | null;
  /**
   * Human-readable explanation that Console can render alongside the
   * convergence badge. The string is generated by the rule layer from the
   * evidence, never authored by a single mutation call site, so wording
   * stays consistent across resources.
   */
  readonly explanation: string;
}

/**
 * A single bounded, redacted entry in the operation history. Body content
 * (raw prompt text, tokens, request bodies) is intentionally absent so the
 * history is safe to surface on every Console page and so it never carries
 * sensitive material into audit/telemetry sinks.
 */
export interface OperationHistoryEntry {
  /** Stable operation identifier (`patch_prompt_command`, etc.). */
  readonly action: string;
  /** Resource identifier the operation targeted, bounded to 200 chars. */
  readonly resource: string;
  /** RFC3339 timestamp the operation was recorded. */
  readonly timestamp: string;
  /** Operator actor identity; `null` for denied/unauthenticated attempts. */
  readonly actor: string | null;
  /** "ok" | "denied" | "error" -- matches the existing audit vocabulary. */
  readonly outcome: "ok" | "denied" | "error";
  /** Bounded reason code for non-OK outcomes (e.g. `revision_conflict`). */
  readonly reason: string | null;
  /** Bounded redacted change metadata (no raw bodies). */
  readonly changes: {
    readonly desiredGeneration: string | null;
    readonly observedGeneration: string | null;
    readonly restartRequired: boolean;
  };
}

/**
 * Reconciliation bundle exposed on every read and mutation response. The
 * runtime fills the evidence and the Console renders the derived `status`
 * alongside the bounded `history`.
 */
export interface ReconciliationView {
  readonly status: ReconciliationStatus;
  readonly history: readonly OperationHistoryEntry[];
}

export const OPERATION_HISTORY_LIMIT = 10;
