#!/usr/bin/env bash
# Generate and persist OpenLIT/Control secrets outside the repository.
#
# The input is a mode-0600 env file under CODEX_HOME (not the tracked
# config/openlit/openlit.env template). Existing strong values are preserved;
# missing or known weak values are rotated. Output values are never printed.

set -euo pipefail

SECRET_FILE=""
while [[ $# -gt 0 ]]; do
	case "$1" in
		--secret-file)
			SECRET_FILE="$2"
			shift 2
			;;
		*)
			echo "bootstrap-secrets.sh: unknown argument: $1" >&2
			exit 1
			;;
	esac
done

CODEX_HOME="${CODEX_HOME:-${HOME:?HOME must be set}/.codex}"
SECRET_FILE="${SECRET_FILE:-$CODEX_HOME/openlit-secrets.env}"

if [[ -d "$SECRET_FILE" ]]; then
	echo "bootstrap-secrets.sh: secret-file path is a directory" >&2
	exit 1
fi

read_secret() {
	local key="$1"
	if [[ ! -f "$SECRET_FILE" ]]; then
		return 0
	fi
	awk -F= -v name="$key" '$1 == name { sub(/^[^=]*=/, ""); print; exit }' "$SECRET_FILE"
}

is_weak() {
	local value="$1"
	[[ ! "$value" =~ ^[0-9a-f]{64}$ ]]
}

generate_secret() {
	if command -v openssl >/dev/null 2>&1; then
		openssl rand -hex 32
	elif command -v python3 >/dev/null 2>&1; then
		python3 -c 'import secrets; print(secrets.token_hex(32))'
	else
		echo "bootstrap-secrets.sh: install openssl or python3 to generate secrets" >&2
		return 1
	fi
}

DB_PASSWORD="$(read_secret OPENLIT_DB_PASSWORD)"
CONTROL_TOKEN="$(read_secret AUTODEV_CONTROL_API_TOKEN)"
OTLP_TOKEN="$(read_secret OPENLIT_OTLP_API_KEY)"
if is_weak "$DB_PASSWORD"; then DB_PASSWORD="$(generate_secret)"; fi
if is_weak "$CONTROL_TOKEN"; then CONTROL_TOKEN="$(generate_secret)"; fi
if is_weak "$OTLP_TOKEN"; then OTLP_TOKEN="$(generate_secret)"; fi

mkdir -p "$(dirname "$SECRET_FILE")"
chmod 0700 "$(dirname "$SECRET_FILE")"
TEMP_FILE="${SECRET_FILE}.tmp.$$"
umask 077
cat > "$TEMP_FILE" <<SECRETS
# Generated by scripts/openlit/bootstrap-secrets.sh — do not commit.
OPENLIT_DB_PASSWORD=$DB_PASSWORD
AUTODEV_CONTROL_API_TOKEN=$CONTROL_TOKEN
OPENLIT_OTLP_API_KEY=$OTLP_TOKEN
SECRETS
chmod 0600 "$TEMP_FILE"
mv -f "$TEMP_FILE" "$SECRET_FILE"
chmod 0600 "$SECRET_FILE"

printf '==> OpenLIT and Control secrets are ready in %s (mode 0600; values redacted)\n' "$SECRET_FILE"
