/**
 * Runtime-side invocation tests for the Playtesting statistical-analysis
 * API. These tests assert the contract that:
 *
 *   1. `RuntimePlaytestStatAnalysis.runWorkedFixture()` produces
 *      intervals at the exact §4 bounds (`[+0.05,+0.16]` and
 *      `[-0.39,-0.21]`) when run against the locked environment.
 *   2. `pairedBootstrapPercentileInterval` rejects non-finite,
 *      empty, or shape-violating inputs as `PlaytestStatisticInputError`.
 *   3. `runWorkedFixture` rejects a mutated fixture with the
 *      `PlaytestStatisticLockDriftError` (the API is the only honest
 *      failure path; silently swapping intervals is forbidden by §4).
 *   4. Transport-level failures produce a categorised error rather than
 *      an uncaught `Error`.
 *
 * The tests skip the long-running fixture unless the dev sets
 * `RUN_PLAYTEST_STATISTICS_FIXTURE=1`; the rest of the suite covers
 * the deterministic branches without paying the 100,000-resample cost.
 */

import assert from "node:assert/strict";
import { mkdtempSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  PlaytestStatisticInputError,
  PlaytestStatisticLockDriftError,
  PlaytestStatisticTransportError,
  RuntimePlaytestStatAnalysis
} from "../src/playtesting/statistics/analysis.ts";
import { resolvePlaytestStatEnvironment } from "../src/playtesting/statistics/environment.ts";
import {
  EXPECTED_LOCK_TAG,
  EXPECTED_SCIENTIFIC_LOCK
} from "../src/playtesting/statistics/lock-manifest.ts";

const RUN_FIXTURE_FLAG = "RUN_PLAYTEST_STATISTICS_FIXTURE";

function fixtureGated(_name: string): boolean {
  return process.env[RUN_FIXTURE_FLAG] === "1";
}

function discardableProjectRoot(): {
  readonly projectRoot: string;
  readonly cleanup: () => void;
} {
  const root = mkdtempSync(path.join(tmpdir(), "autodev-playtest-stat-run-"));
  const realRoot = realpathSync(root);
  writeFileSync(
    path.join(realRoot, "pyproject.toml"),
    [
      "[project]",
      `name = "autodev-playtest-statistics"`,
      `version = "0.1.0"`,
      `description = "fixture"`,
      `requires-python = "${EXPECTED_SCIENTIFIC_LOCK.python}"`,
      "dependencies = [",
      `    "numpy==${EXPECTED_SCIENTIFIC_LOCK.numpy}",`,
      `    "scipy==${EXPECTED_SCIENTIFIC_LOCK.scipy}",`,
      `    "statsmodels==${EXPECTED_SCIENTIFIC_LOCK.statsmodels}",`,
      "]",
      "[tool.uv]",
      "managed = true",
      "package = false"
    ].join("\n") + "\n"
  );
  writeFileSync(
    path.join(realRoot, "uv.lock"),
    [
      "# generated by uv",
      "version = 1",
      "revision = 3",
      `requires-python = "${EXPECTED_SCIENTIFIC_LOCK.python}"`,
      "[[package]]",
      `name = "scipy"`,
      `version = "${EXPECTED_SCIENTIFIC_LOCK.scipy}"`,
      "[[package]]",
      `name = "numpy"`,
      `version = "${EXPECTED_SCIENTIFIC_LOCK.numpy}"`,
      "[[package]]",
      `name = "statsmodels"`,
      `version = "${EXPECTED_SCIENTIFIC_LOCK.statsmodels}"`
    ].join("\n") + "\n"
  );
  writeFileSync(path.join(realRoot, "PYTHON_README.md"), "# test stub\n");
  return {
    projectRoot: realRoot,
    cleanup: () => {
      try {
        rmSync(realRoot, { recursive: true, force: true });
      } catch {
        // ignore
      }
    }
  };
}

test("EXPECTED_LOCK_TAG carries the §4 pin order", () => {
  assert.equal(
    EXPECTED_LOCK_TAG,
    "scipy-1.17.0/numpy-2.3.5/statsmodels-0.14.6"
  );
});

test("RuntimePlaytestStatAnalysis rejects empty bootstrap arrays", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: []
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects NaN bootstrap inputs as input errors", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [Number.NaN, 0, 1]
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects non-positive resamples as input errors", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        resamples: 0
      }),
    PlaytestStatisticInputError
  );
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        resamples: -1
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects confidenceLevel outside (0,1)", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0],
        confidenceLevel: 0
      }),
    PlaytestStatisticInputError
  );
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0],
        confidenceLevel: 1
      }),
    PlaytestStatisticInputError
  );
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0],
        confidenceLevel: 1.5
      }),
    PlaytestStatisticInputError
  );
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0],
        confidenceLevel: Number.NaN
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects non-integer seeds", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0],
        seed: 1.5
      }),
    PlaytestStatisticInputError
  );
  await assert.rejects(
    () =>
      analysis.pairedBootstrapPercentileInterval({
        array: [1, 0, 0],
        seed: Number.POSITIVE_INFINITY
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects empty multiplicity pvalue arrays", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.multiplicityAdjustedPValues({
        pvalues: []
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects out-of-range multiplicity pvalues", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  await assert.rejects(
    () =>
      analysis.multiplicityAdjustedPValues({
        pvalues: [-0.01, 0.5]
      }),
    PlaytestStatisticInputError
  );
  await assert.rejects(
    () =>
      analysis.multiplicityAdjustedPValues({
        pvalues: [1.5]
      }),
    PlaytestStatisticInputError
  );
});

test("RuntimePlaytestStatAnalysis rejects unsupported multiplicity methods", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    fixturePathOverride: "/nonexistent-fixture.json"
  });
  // We deliberately pass a wrong method name through the structured
  // input; the runtime validator must reject it before reaching the
  // worker.
  await assert.rejects(
    () =>
      analysis.multiplicityAdjustedPValues({
        pvalues: [0.01, 0.5],
        method: "unsupported-method" as "fdr_bh"
      }),
    PlaytestStatisticInputError
  );
});

test(
  "§4 worked fixture: pairedBootstrapPercentileInterval produces the exact expected bounds",
  {
    skip:
      !fixtureGated(RUN_FIXTURE_FLAG) &&
      "Set RUN_PLAYTEST_STATISTICS_FIXTURE=1 to exercise the full §4 fixture (~10s)."
  },
  async () => {
    const analysis = new RuntimePlaytestStatAnalysis();
    // The callback form preserves the element type as `number`;
    // `.fill()` on `Array.from({length})` would widen it to `unknown[]`,
    // which the PlaytestBootstrapInput contract cannot accept.
    // eslint-disable-next-line e18e/prefer-array-fill -- the lint-suggested `.fill()` form widens the element type to `unknown` and breaks the PlaytestBootstrapInput contract.
    const primary: number[] = Array.from({ length: 10 }, () => 1).concat(
      // eslint-disable-next-line e18e/prefer-array-fill -- see primary arm above
      Array.from({ length: 90 }, () => 0)
    );
    const interval = await analysis.pairedBootstrapPercentileInterval({
      array: primary
    });
    assert.equal(interval.method, "percentile-bootstrap");
    assert.equal(interval.libraryVersion, EXPECTED_LOCK_TAG);
    assert.equal(interval.confidenceLevel, 0.95);
    assert.equal(interval.resamples, 100_000);
    assert.equal(interval.seed, "42");
    assert.ok(Math.abs(interval.lower - 0.05) < 0.005);
    assert.ok(Math.abs(interval.upper - 0.16) < 0.005);
  }
);

test(
  "§4 worked fixture: runWorkedFixture rejects a mutated fixture with PlaytestStatisticLockDriftError",
  {
    skip:
      !fixtureGated(RUN_FIXTURE_FLAG) &&
      "Set RUN_PLAYTEST_STATISTICS_FIXTURE=1 to exercise the full §4 fixture (~10s)."
  },
  async () => {
    const tampered = {
      schema: "autodev-playtest-statistic-fixture-v1",
      description: "tampered",
      expectedLibraryVersion: EXPECTED_LOCK_TAG,
      expectedResamples: 100_000,
      expectedConfidenceLevel: 0.95,
      expectedSeed: 42,
      expectedMethods: ["percentile-bootstrap"],
      primary: {
        metricId: "completion",
        // eslint-disable-next-line e18e/prefer-array-fill -- see §4 worked-fixture comment above.
        pairedDifferences: Array.from({ length: 99 }, () => 0).concat([1]),
        expectedInterval: { lower: 0.99, upper: 1 }
      },
      guardrail: {
        metricId: "clarity",
        // eslint-disable-next-line e18e/prefer-array-fill -- see §4 worked-fixture comment above.
        pairedDifferences: Array.from({ length: 99 }, () => 0).concat([-1]),
        expectedInterval: { lower: -1, upper: -0.99 }
      }
    };
    const text = JSON.stringify(tampered);
    const analysis = new RuntimePlaytestStatAnalysis({
      fixturePathOverride: "/does-not-matter.json",
      fixtureTextOverride: text
    });
    await assert.rejects(analysis.runWorkedFixture(), (error: unknown) => {
      if (!(error instanceof PlaytestStatisticLockDriftError)) return false;
      // The contract violation references the offending metric so an
      // operator can trace which arm of the fixture drifted.
      assert.ok(
        /completion/u.test(error.message) || /clarity/u.test(error.message),
        `Drift error should call out the failing metric: ${error.message}`
      );
      return true;
    });
  }
);

test("RuntimePlaytestStatAnalysis exposes the on-disk environment fingerprint", () => {
  const analysis = new RuntimePlaytestStatAnalysis();
  const fingerprint = analysis.environmentFingerprint();
  assert.match(fingerprint, /^[a-f0-9]{64}$/u);
});

test("transport failures reference a categorised error rather than a plain Error", async () => {
  const analysis = new RuntimePlaytestStatAnalysis({
    uvBinary: "/no/such/binary",
    timeoutMs: 5000,
    fixturePathOverride: "/does-not-matter.json"
  });
  await assert.rejects(
    analysis.pairedBootstrapPercentileInterval({
      array: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    }),
    (error: unknown) => error instanceof PlaytestStatisticTransportError
  );
});

test("Run-scoped environment resolution does not require a fixture", () => {
  const env = resolvePlaytestStatEnvironment();
  assert.match(env.contentHash, /^[a-f0-9]{64}$/u);
  assert.ok(env.pyprojectPath.endsWith("pyproject.toml"));
  assert.ok(env.uvLockPath.endsWith("uv.lock"));
});

// Helper kept available for future sandboxed-environment experiments.
void discardableProjectRoot;
