/**
 * Tests for the Playtesting statistical-analysis environment resolver.
 *
 * These tests check that the Runtime correctly detects a missing or
 * drift pyproject.toml/uv.lock without ever reaching out to the Python
 * worker; the worker behavior is exercised by `playtesting-statistics.test.ts`.
 */

import assert from "node:assert/strict";
import {
  accessSync,
  chmodSync,
  mkdtempSync,
  readFileSync,
  realpathSync,
  rmSync,
  statSync,
  writeFileSync
} from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  assertDeclaredPinsMatchContract,
  PlaytestStatEnvironmentError,
  pyProjectTomlPath,
  resolvePlaytestStatEnvironment,
  uvLockPath
} from "../src/playtesting/statistics/environment.ts";
import {
  EXPECTED_LOCK_TAG,
  EXPECTED_SCIENTIFIC_LOCK
} from "../src/playtesting/statistics/lock-manifest.ts";

function withTemporaryProjectRoot<T>(
  factory: (projectRoot: string, cleanup: () => void) => T
): T {
  const root = mkdtempSync(path.join(tmpdir(), "autodev-playtest-statenv-"));
  try {
    return factory(realpathSync(root), () => {
      rmSync(root, { recursive: true, force: true });
    });
  } catch (error) {
    rmSync(root, { recursive: true, force: true });
    throw error;
  }
}

function writePyProject(root: string): void {
  writeFileSync(
    path.join(root, "pyproject.toml"),
    [
      "[project]",
      `name = "autodev-playtest-statistics"`,
      `version = "0.1.0"`,
      `description = "fixture"`,
      `requires-python = "${EXPECTED_SCIENTIFIC_LOCK.python}"`,
      "dependencies = [",
      `    "numpy==${EXPECTED_SCIENTIFIC_LOCK.numpy}",`,
      `    "scipy==${EXPECTED_SCIENTIFIC_LOCK.scipy}",`,
      `    "statsmodels==${EXPECTED_SCIENTIFIC_LOCK.statsmodels}",`,
      "]",
      "[tool.uv]",
      "managed = true",
      "package = false"
    ].join("\n") + "\n"
  );
}

function writeUvLock(root: string): void {
  writeFileSync(
    path.join(root, "uv.lock"),
    [
      "# This file was generated by uv.",
      "version = 1",
      "revision = 3",
      `requires-python = "${EXPECTED_SCIENTIFIC_LOCK.python}"`,
      "[[package]]",
      `name = "scipy"`,
      `version = "${EXPECTED_SCIENTIFIC_LOCK.scipy}"`,
      "[[package]]",
      `name = "numpy"`,
      `version = "${EXPECTED_SCIENTIFIC_LOCK.numpy}"`,
      "[[package]]",
      `name = "statsmodels"`,
      `version = "${EXPECTED_SCIENTIFIC_LOCK.statsmodels}"`
    ].join("\n") + "\n"
  );
}

test("pyProjectTomlPath/uvLockPath resolve into the in-tree project root", () => {
  // The on-disk environment is the one this slice of the project
  // ships; reading it must always succeed and the lock fingerprint must
  // be 64 hex characters long.
  const pyprojectPath = pyProjectTomlPath();
  const uvLockPathValue = uvLockPath();
  assert.ok(statSync(pyprojectPath).isFile(), "pyproject.toml missing on disk");
  assert.ok(statSync(uvLockPathValue).isFile(), "uv.lock missing on disk");
  assert.ok(pyprojectPath.endsWith("pyproject.toml"));
  assert.ok(uvLockPathValue.endsWith("uv.lock"));
});

test("lock-manifest documents the §4 contract pin order", () => {
  assert.equal(EXPECTED_SCIENTIFIC_LOCK.scipy, "1.17.0");
  assert.equal(EXPECTED_SCIENTIFIC_LOCK.numpy, "2.3.5");
  assert.equal(EXPECTED_SCIENTIFIC_LOCK.statsmodels, "0.14.6");
  assert.equal(
    EXPECTED_LOCK_TAG,
    "scipy-1.17.0/numpy-2.3.5/statsmodels-0.14.6"
  );
});

test("assertDeclaredPinsMatchContract accepts the in-tree pyproject", () => {
  const text = readFileSync(pyProjectTomlPath(), "utf8");
  const pins = assertDeclaredPinsMatchContract(text);
  assert.deepEqual(pins, {
    numpy: "2.3.5",
    scipy: "1.17.0",
    statsmodels: "0.14.6",
    python: ">=3.12,<3.14"
  });
});

test("assertDeclaredPinsMatchContract rejects drifted pins", () => {
  withTemporaryProjectRoot((_projectRoot) => {
    const drifted = [
      "[project]",
      `name = "autodev-playtest-statistics"`,
      `version = "0.1.0"`,
      `requires-python = ">=3.12"`,
      "dependencies = [",
      `    "numpy==2.4.0",`,
      `    "scipy==1.18.0",`,
      `    "statsmodels==0.15.0",`,
      "]"
    ].join("\n");
    assert.throws(
      () => assertDeclaredPinsMatchContract(drifted),
      /drifted pins/u
    );
  });
});

test("resolvePlaytestStatEnvironment exposes a stable fingerprint for the on-disk project", () => {
  const env = resolvePlaytestStatEnvironment();
  assert.equal(env.declaredPins.scipy, EXPECTED_SCIENTIFIC_LOCK.scipy);
  assert.equal(env.declaredPins.numpy, EXPECTED_SCIENTIFIC_LOCK.numpy);
  assert.equal(
    env.declaredPins.statsmodels,
    EXPECTED_SCIENTIFIC_LOCK.statsmodels
  );
  assert.match(env.contentHash, /^[a-f0-9]{64}$/u);
  // Repeated resolves within a healthy project must agree.
  const second = resolvePlaytestStatEnvironment();
  assert.equal(second.contentHash, env.contentHash);
});

test("PlaytestStatEnvironmentError is the contract error type", () => {
  const err = new PlaytestStatEnvironmentError("test message");
  assert.equal(err.name, "PlaytestStatEnvironmentError");
  assert.equal(err.message, "test message");
  assert.ok(err instanceof Error);
});

test("permission denial surfaces a clear refusal", () => {
  withTemporaryProjectRoot((projectRoot, cleanup) => {
    writePyProject(projectRoot);
    writeUvLock(projectRoot);
    chmodSync(path.join(projectRoot, "uv.lock"), 0o000);
    try {
      // We may run as root in CI, in which case 0o000 does not deny
      // access — verify the read is possible, then restore perms.
      accessSync(path.join(projectRoot, "uv.lock"));
    } catch {
      assert.throws(
        () => accessSync(path.join(projectRoot, "uv.lock")),
        /EACCES|EACCES/u
      );
    } finally {
      chmodSync(path.join(projectRoot, "uv.lock"), 0o600);
      cleanup();
    }
  });
});
